// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Semicrol.Pallets.Models
{
    [Table("Pallets_BobinasLiberacion", Schema = "dbo")]
    public partial class Pallets_BobinasLiberacion
    {
        [Key]
        public int identificador { get; set; }
        public int? idPallet { get; set; }
        public int? idBobina { get; set; }
        [StringLength(3)]
        public string proceso { get; set; }
    }
}