// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Semicrol.Pallets.Models
{
    [Table("pallets_asociados_cc", Schema = "dbo")]
    public partial class pallets_asociados_cc
    {
        [Key]
        public int identificador { get; set; }
        public int ref_pallet { get; set; }
        public int ref_pallet_origen { get; set; }
        public int? ref_operario { get; set; }
        public byte? turno { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? fecha_turno { get; set; }
        public byte? anulado { get; set; }
        [StringLength(20)]
        public string usuario_anulacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? fecha_anulacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? hora_anulacion { get; set; }
        [StringLength(20)]
        public string usuario_creacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? fecha_creacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? hora_creacion { get; set; }
    }
}