// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Semicrol.Pallets.Models
{
    [Table("pedidos", Schema = "dbo")]
    public partial class pedidos
    {
        [Key]
        public int identificador { get; set; }
        public int? numero_pedido { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? fecha_pedido { get; set; }
        public int? codigo_cliente { get; set; }
        [StringLength(40)]
        public string nombre_cliente { get; set; }
        [StringLength(8)]
        public string codigo_formato { get; set; }
        [StringLength(120)]
        public string nombre_formato { get; set; }
        [StringLength(10)]
        public string codigo_producto { get; set; }
        [StringLength(16)]
        public string suref_cliente { get; set; }
        [StringLength(3)]
        public string codigo_unimedida { get; set; }
        [StringLength(1)]
        public string indicador { get; set; }
        [StringLength(1)]
        public string ind_modificado { get; set; }
        [StringLength(1)]
        public string ind_anulado { get; set; }
        [Column(TypeName = "numeric(18, 3)")]
        public decimal? kilos { get; set; }
        [Column(TypeName = "numeric(18, 3)")]
        public decimal? metros { get; set; }
        public int? unidades { get; set; }
        [Column(TypeName = "numeric(18, 3)")]
        public decimal? conversion { get; set; }
        [StringLength(40)]
        public string observaciones { get; set; }
        [StringLength(1)]
        public string tipo_etiquetado { get; set; }
        [StringLength(10)]
        public string logotipo_etiqueta { get; set; }
        [StringLength(1)]
        public string tipo_pedido { get; set; }
        [StringLength(1)]
        public string ind_desglose { get; set; }
        [StringLength(2)]
        public string tipo_embalaje { get; set; }
        [StringLength(1)]
        public string tipo_peso_etiq { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? fecha { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? hora { get; set; }
        [StringLength(1)]
        public string estado_fabricacion { get; set; }
        public int? numero_pallets { get; set; }
        [StringLength(8)]
        public string usuario_creacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? fecha_creacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? hora_creacion { get; set; }
        [StringLength(8)]
        public string usuario_actua { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? fecha_actua { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? hora_actua { get; set; }
        public int? etiq_embalaje { get; set; }
        [StringLength(1)]
        public string ind_desglose2 { get; set; }
        public int? etiq_bobinas { get; set; }
        [StringLength(20)]
        public string supdo_cliente { get; set; }
        [StringLength(3)]
        public string delegacion { get; set; }
        [StringLength(1)]
        public string ind_usoaliment { get; set; }
        [StringLength(8)]
        public string ind_etiqcli { get; set; }
        public int? num_etiqcli { get; set; }
        [StringLength(20)]
        public string proveed_cliente { get; set; }
        [Column(TypeName = "decimal(7, 2)")]
        public decimal? ancho { get; set; }
        [Column(TypeName = "decimal(15, 5)")]
        public decimal? espesor { get; set; }
        [StringLength(9)]
        public string color { get; set; }
        public short? unidades_pale { get; set; }
        [StringLength(5)]
        public string codigo_material { get; set; }
        [StringLength(1)]
        public string ind_metmot { get; set; }
        [Column(TypeName = "numeric(18, 0)")]
        public decimal? metmot_bobina { get; set; }
        public int ean_formato { get; set; }
        public int? orden_fabric { get; set; }
        public short? secuencia { get; set; }
        [StringLength(1)]
        public string ind_kilos_factura { get; set; }
        [StringLength(8)]
        public string etiqueta_bobina { get; set; }
        [StringLength(8)]
        public string etiqueta_pale { get; set; }
    }
}