// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Semicrol.Pallets.Models
{
    [Table("procesos", Schema = "dbo")]
    public partial class procesos
    {
        [Key]
        public int identificador { get; set; }
        public int? ref_pedido { get; set; }
        public int? orden_proceso { get; set; }
        [StringLength(2)]
        public string proceso { get; set; }
        public int? ref_maquina { get; set; }
        public int? ref_seccion { get; set; }
        [StringLength(10)]
        public string codigo_producto { get; set; }
        [StringLength(120)]
        public string nombre_producto { get; set; }
        [Column(TypeName = "numeric(18, 3)")]
        public decimal? peso_unitario { get; set; }
        [Column(TypeName = "numeric(18, 3)")]
        public decimal? metros_bobina { get; set; }
        [Column(TypeName = "numeric(18, 3)")]
        public decimal? kilos { get; set; }
        [Column(TypeName = "numeric(18, 3)")]
        public decimal? metros { get; set; }
        public int? unidades { get; set; }
        [StringLength(3)]
        public string codigo_unimedida { get; set; }
        [Column(TypeName = "numeric(18, 3)")]
        public decimal? destare_bobina { get; set; }
        [Column(TypeName = "numeric(18, 3)")]
        public decimal? destare_pallet { get; set; }
        [Column(TypeName = "numeric(18, 3)")]
        public decimal? desviacion_mas { get; set; }
        [Column(TypeName = "numeric(18, 3)")]
        public decimal? desviacion_menos { get; set; }
        [StringLength(1)]
        public string tipo_desviacion { get; set; }
        [Column(TypeName = "numeric(18, 3)")]
        public decimal? peso_metro { get; set; }
        [StringLength(8)]
        public string usuario_creacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? fecha_creacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? hora_creacion { get; set; }
        [StringLength(8)]
        public string usuario_actua { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? fecha_actua { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? hora_actua { get; set; }
        public int? Orden { get; set; }
        [StringLength(1)]
        public string Terminado { get; set; }
        [Column(TypeName = "numeric(18, 0)")]
        public decimal? metrosbob_teo { get; set; }
        [Column(TypeName = "numeric(18, 0)")]
        public decimal? pesobob_teo { get; set; }
        public short? bobinas_simult { get; set; }
        public short? multiplos { get; set; }
        public short? estado { get; set; }
        public short? preparada { get; set; }
        public int? color_p { get; set; }
        public short? mandriles { get; set; }
        public short? tintas { get; set; }
    }
}